### ISSUE TITLE
Prevent users from starting game without a single question added

### ISSUE THREAD

**Issue by kanes115** [kanes115/what-if-backend#11]

**Comment by kanes115** [comment]
@Baksztag I send "error" with "reason": "no_questions_added" in response to setting ready with no questions in room

**Comment by kanes115** [comment]
This is the same as #16

**Comment by Baksztag** [comment]
Fixed in https://github.com/Baksztag/what-if-frontend/commit/6693678c742fd04d7acad2a5a9ccf094c388f480
