### ISSUE TITLE
Prevent users from adding questions in ready state

### ISSUE THREAD

**Issue by kanes115** [kanes115/what-if-backend#13]

**Comment by kanes115** [comment]
@Baksztag I will be sending message "error" with payload `{"reason": "You cannot add questions in ready state"}`

**Comment by kanes115** [comment]
Waiting for frontend

**Comment by Baksztag** [comment]
Resolved in https://github.com/Baksztag/what-if-frontend/commit/2a05a85f07db8aad4a50fae326b87cd7d535ce98
