### ISSUE TITLE
Investigate a situation when room creation is imipossible

### ISSUE THREAD

**Issue by kanes115** [kanes115/what-if-backend#25]
There might be a bug. Steps to reproduce:
- Sign up
- Pass your nickname
- try to create a room

Then nothings happens :( We need to investigate this

**Comment by kanes115** [comment]
what happens in simple terms is: after setting display-name (aka giving our nickname) you receive "cannot join" to the room (phoenix channel)

**Comment by Baksztag** [comment]
Resolved in https://github.com/Baksztag/what-if-frontend/commit/ffb9f5581e7958dcc914c7a0da49757c17dc4578
