### ISSUE TITLE
Displaying errors on logging in and signing up

### ISSUE THREAD

**Issue by kanes115** [kanes115/what-if-backend#9]
Currently we don't even tell user that the password is too short or incorrect

**Comment by kanes115** [comment]
@Baksztag, isn't this already closed?

**Comment by Baksztag** [comment]
Implemented in https://github.com/Baksztag/what-if-frontend/commit/7fd2c25d743d0724972776f9b038a5a2ae533b72

**Comment by Baksztag** [comment]
Completed in https://github.com/Baksztag/what-if-frontend/commit/02cbe9dfbac9e5a228f09dc1dc8868f096584810
